##==============================================================================
## Shortest Path Routing Algorithm
##
## @description: Makefile for router.java
## @author: Elisha Lai
## @version: 1.0 25/11/2016
##==============================================================================

all:
	@echo "Compiling..."
	javac *.java

.PHONY: clean

clean:
	@echo "Cleaning..."
	find . -name "*.class" -delete
